name: Run Infra tests

on:
  pull_request:
    paths:
      - '**.tf'
      - '.tflint.hcl'
      - 'infra/Makefile'
  push:
    branches:
      - main

jobs:
  tflint:
    name: Run TFLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.58.1

      - name: Run make lint
        run: make lint
        working-directory: ./infra
